FROM nginx:alpine
COPY . /usr/share/nginx/html

# documentation
# EXPOSE 80 // defalut port
# CMD [ "nginx", "-g", "deamon-off;" ] // default executable for executing container. ndinx passes image in.

